### ISSUE TITLE
Retina media queries

### ISSUE THREAD

**Issue by CoralSilver** [twolfson/spritesheet-templates#44]
Where would I be able to change the media queries that are output for retina images?

I believe the existing ones are insufficient:
```
@media (-webkit-min-device-pixel-ratio: 2),
       (min-resolution: 192dpi) {
```
Want it to be something like: 
```
@media only screen and (-webkit-min-device-pixel-ratio: 1.3), 
only screen and (min--moz-device-pixel-ratio: 1.3), 
only screen and (-o-min-device-pixel-ratio: 1.3 / 1), 
only screen and (min-resolution: 125dpi), 
only screen and (min-resolution: 1.3dppx) {
```
Don't know why, but existing one is working on static prototype, but not Angular app on my Macbook Pro with Retina screen.

**Comment by twolfson** [comment]
We went with the 2x since that's the threshold for retina. Here's the reference source for our queries:

https://css-tricks.com/snippets/css/retina-display-media-query/

That being said, I think this is too much of an edge case to warrant a new option. Instead, I would recommend doing an override. There are a few ways to do this via `spritesmith`:

# Overriding in CSS preprocessor
If you are using a CSS preprocessor (e.g. SASS), then we can override the existing mixin to fit our needs:

```sass
# Import variables and mixins define by spritesmith
import "spritesmith.scss';

# Override the retina sprite mixin
#   https://github.com/twolfson/spritesheet-templates/blob/10.0.0/lib/templates/scss_retina.template.handlebars#L63-L73
@mixin retina-sprite($retina-group) {
  $normal-sprite: nth($retina-group, 2);
  $retina-sprite: nth($retina-group, 3);
  @include sprite($normal-sprite);

  @media only screen and (-webkit-min-device-pixel-ratio: 1.3), 
        only screen and (min--moz-device-pixel-ratio: 1.3), 
        only screen and (-o-min-device-pixel-ratio: 1.3 / 1), 
        only screen and (min-resolution: 125dpi), 
        only screen and (min-resolution: 1.3dppx) {
    @include sprite-image($retina-sprite);
    @include sprite-background-size($normal-sprite);
  }
}
```

# Using a custom template
`spritesmith` supports using custom templates (which can be either inherited from other ones or new). Documentation on that can be found here:

https://github.com/Ensighten/grunt-spritesmith/tree/6.1.1#templating

https://github.com/Ensighten/grunt-spritesmith/tree/6.1.1#handlebars-template

https://github.com/Ensighten/grunt-spritesmith/tree/6.1.1#handlebars-inheritance

**Comment by CoralSilver** [comment]
Thanks for the quick response.  I tried overriding it, but must be doing something wrong. I created a new partial named ```_spritesmith.scss``` with the code you included and imported the file at the end of my main scss file.  But the output is the same.

**Comment by twolfson** [comment]
Fixed up a quote mismatch in the example I provided (but I'm guessing you caught that).

Can you verify that the import/override comes before any invocation of `@include sprite/sprites/retina_sprite/retina_sprites`?

**Comment by CoralSilver** [comment]
Yeah caught the mismatch thanks.  I don't think I am invoking ```@include sprite/sprites/retina_sprite/retina_sprites.```  Where would that be?  I tried putting the @import before my @import of the output _sprite.scss file, but apparently is it supposed to go afterwards.

**Comment by twolfson** [comment]
I think it would be easier if we have a document to reference. Can you paste a copy of your SCSS to gist.github.com?

**Comment by CoralSilver** [comment]
Thanks, let me know if you need to see anything else.
https://gist.github.com/CoralSilver/46c2e1d307f783da9d2b

**Comment by twolfson** [comment]
Can you upload the SCSS that invokes the mixins as well (i.e. whatever processes `sass/elements/_sprite.scss`)?

**Comment by CoralSilver** [comment]
Ahh ok I understand the needed order now. Thanks so much. I got it working.

**Comment by twolfson** [comment]
Ah, awesome. That's great to hear =)
